### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by XuLingLong** [qbammey/adaptive_cfa_forensics#2]
When I try to use anaconda to bulid a virtual environment  based on the "readme",I meet the problem called that "No module named 'numpy.core._multiarray_umath",.I google it and try to uninstall and install numpy again and again , but it dose not work.
Can you tell me the specific version of python bag mentioned in "readme"? Inclunding numpy, pytorch,PIL and so on....
Thank you!

**Comment by XuLingLong** [comment]
D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\python.exe F:/1ImageForensics/adaptive_cfa_forensics/src/train_model.py
D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed while importing _multiarray_umath: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/1ImageForensics/adaptive_cfa_forensics/src/train_model.py", line 14, in <module>
    import numpy as np
  File "D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\__init__.py", line 145, in <module>
    from . import core
  File "D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "D:\YuLuo\ProgramData\Anaconda3\envs\XLLPy3.8Pytorch1.7.1\python.exe"
  * The NumPy version is: "1.20.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: 找不到指定的模块。


Process finished with exit code 1





HOW CAN I FIX THIS PROBLEM?ANY ONE HAS MEET IT?
